"""SystemModel IR -> SysML v2 textual notation.

Deterministic. No model is involved: by the time we are here the hard thinking is done and the
IR is validated, so emission is a mechanical walk. That is deliberate -- a generated artefact
that a language model touched is an artefact you have to re-verify.

The emitted subset: package, part def / part usage, port def / port usage, interface (bind),
attribute, state def with parallel regions and transitions, requirement def with satisfy and
verify, and allocation from logical parts to their Modelica realisation.

`parse_back()` re-reads our own output and reconstructs the element graph. Comparing that to
the IR is a real, dependency-free round-trip check: no Java, no pilot implementation needed.

Owner: B.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path

from ..ir.system import Block, Connection, StateMachine, SystemModel

INDENT = "    "


def _ident(raw: str) -> str:
    """SysML identifiers: letters, digits, underscore. Anything else gets folded."""
    out = re.sub(r"[^A-Za-z0-9_]", "_", raw.strip())
    return out if out and not out[0].isdigit() else f"e_{out}"


def _doc(text: str | None, depth: int) -> list[str]:
    if not text:
        return []
    pad = INDENT * depth
    body = text.replace("*/", "* /").strip()
    return [f"{pad}doc /* {body} */"]


def _trace_comment(*, requirements: list[str], claims: list[str], depth: int) -> list[str]:
    if not requirements and not claims:
        return []
    pad = INDENT * depth
    bits = []
    if requirements:
        bits.append("satisfies " + ", ".join(requirements))
    if claims:
        bits.append("evidence " + ", ".join(claims[:4]) + ("..." if len(claims) > 4 else ""))
    return [f"{pad}// @trace {'; '.join(bits)}"]


class SysMLEmitter:
    def __init__(self, model: SystemModel) -> None:
        self.m = model
        self.lines: list[str] = []

    # ------------------------------------------------------------------ helpers
    def _w(self, depth: int, text: str = "") -> None:
        self.lines.append(f"{INDENT * depth}{text}" if text else "")

    # ------------------------------------------------------------------ sections
    def emit(self) -> str:
        m = self.m
        pkg = _ident(m.name)
        self._w(0, f"package {pkg} {{")
        self._w(1, f"// Generated by SpecAlive from {len(m.sources)} evidence sources.")
        self._w(1, f"// IR schema {m.schema_version}. Domains: {', '.join(m.domains)}.")
        self._w(0)

        self._emit_port_defs()
        self._emit_requirements()
        self._emit_part_defs()
        self._emit_system()
        self._emit_state_machines()
        self._emit_allocations()
        self._emit_verification()

        self._w(0, "}")
        return "\n".join(self.lines) + "\n"

    def _emit_port_defs(self) -> None:
        """One port def per distinct (domain, direction) pair actually used."""
        seen: dict[tuple[str, str], str] = {}
        for b in self.m.blocks:
            for p in b.ports:
                # Name by domain AND direction: two port defs that differ only in direction
                # must not collide, or the emitted package declares the same name twice.
                seen.setdefault(
                    (p.domain, p.direction),
                    f"{_ident(p.domain.title())}{_ident(p.direction.title())}Port",
                )
        if not seen:
            return
        self._w(1, "// ---------------------------------------------------------------- ports")
        for (domain, direction), name in sorted(seen.items(), key=lambda kv: kv[1]):
            self._w(1, f"port def {name} {{")
            self._w(2, f"attribute domain : String default \"{domain}\";")
            self._w(2, f"attribute direction : String default \"{direction}\";")
            self._w(1, "}")
        self._w(0)

    def _emit_requirements(self) -> None:
        if not self.m.requirements:
            return
        self._w(1, "// --------------------------------------------------------- requirements")
        for r in self.m.requirements:
            rid = _ident(r.id)
            status = f" // status: {r.status}" + (f", superseded by {r.superseded_by}" if r.superseded_by else "")
            self._w(1, f"requirement def {rid} {{{status}")
            self._w(2, f'doc /* {r.text.strip()} */')
            if r.authority:
                self._w(2, f'attribute authority : String default "{r.authority}";')
            if r.priority != "unknown":
                self._w(2, f'attribute priority : String default "{r.priority}";')
            if r.verification_method:
                self._w(2, f'attribute verificationMethod : String default "{r.verification_method}";')
            for cid in r.provenance.claim_ids[:6]:
                claim = self.m.claim(cid)
                if claim:
                    self._w(2, f"// @evidence {claim.ref()}: {claim.quote[:110]}")
            self._w(1, "}")
        self._w(0)

    def _emit_part_defs(self) -> None:
        """A part def per distinct block kind, so repeated equipment shares a definition."""
        kinds: dict[str, Block] = {}
        for b in self.m.blocks:
            kinds.setdefault(_ident(b.kind or b.name), b)
        self._w(1, "// ------------------------------------------------------------ part defs")
        for kind, exemplar in sorted(kinds.items()):
            self._w(1, f"part def {kind} {{")
            self.lines += _doc(exemplar.description or exemplar.kind, 2)
            for p in exemplar.ports:
                self._w(
                    2,
                    f"port {_ident(p.name)} : "
                    f"{_ident(p.domain.title())}{_ident(p.direction.title())}Port;",
                )
            for prm in exemplar.parameters:
                self._w(2, f"attribute {_ident(prm.name)} : Real; // {prm.quantity.unit or 'dimensionless'}")
            self._w(1, "}")
        self._w(0)

    def _emit_system(self) -> None:
        m = self.m
        self._w(1, "// -------------------------------------------------------- system usage")
        self._w(1, f"part {_ident(m.name)}System {{")
        for b in m.blocks:
            self._emit_part_usage(b, depth=2)
        self._w(0)
        for c in m.connections:
            self._emit_connection(c, depth=2)
        self._w(0)
        for s in m.signals:
            tag = "sensor" if s.role == "sensor" else "actuator"
            binding = f" // bound to {s.binding}" if s.binding else ""
            self._w(2, f"attribute {_ident(s.name)} : {_sysml_type(s.datatype)}; // {tag}{binding}")
        for il in m.interlocks:
            self._w(2, f"// @interlock {il.sense} on {il.actuator}: {il.condition}")
        self._w(1, "}")
        self._w(0)

    def _emit_part_usage(self, b: Block, depth: int) -> None:
        kind = _ident(b.kind or b.name)
        self._w(depth, f"part {_ident(b.id)} : {kind} {{")
        self.lines += _trace_comment(
            requirements=[_ident(r) for r in b.provenance.requirement_ids],
            claims=b.provenance.claim_ids,
            depth=depth + 1,
        )
        if b.abstracted_into:
            self._w(
                depth + 1,
                f"// @abstraction physically distinct, merged into {b.abstracted_into} for simulation only",
            )
        if b.physical_only:
            self._w(depth + 1, "// @scope architecture only: not present in the executable model")
        for prm in b.parameters:
            q = prm.quantity
            if q.value is not None:
                unit = f" // {q.unit}" if q.unit else ""
                self._w(depth + 1, f"attribute redefines {_ident(prm.name)} = {q.value};{unit}")
        self._w(depth, "}")

    def _emit_connection(self, c: Connection, depth: int) -> None:
        (sb, sp), (tb, tp) = c.endpoints()
        label = f" // {c.medium}" if c.medium else ""
        self._w(depth, f"interface {_ident(c.id)} connect {_ident(sb)}.{_ident(sp)} to {_ident(tb)}.{_ident(tp)};{label}")
        if c.series_elements:
            self._w(depth, f"{INDENT}// @series {', '.join(c.series_elements)}")
        self.lines += _trace_comment(
            requirements=[_ident(r) for r in c.provenance.requirement_ids],
            claims=[],
            depth=depth,
        )

    def _emit_state_machines(self) -> None:
        for sm in self.m.state_machines:
            self._w(1, f"// ---------------------------------------------------- behaviour: {sm.name}")
            self._w(1, f"state def {_ident(sm.name)} {{")
            for region in sm.regions:
                nested = len(sm.regions) > 1
                d = 2
                if nested:
                    self._w(2, f"state {_ident(region)}Region parallel {{")
                    d = 3
                for s in sm.states_in(region):
                    entry = " // initial" if s.initial else ""
                    self._w(d, f"state {_ident(s.id)} {{{entry}")
                    self.lines += _doc(s.description, d + 1)
                    for sig, expr in s.actions.items():
                        self._w(d + 1, f"do action set_{_ident(sig)} {{ /* {sig} := {expr} */ }}")
                    self._w(d, "}")
                for t in sm.transitions:
                    src = sm.state(t.source_state)
                    if src is None or src.region != region:
                        continue
                    extra = ""
                    if t.forks:
                        extra = f" // fork -> {', '.join(t.forks)}"
                    elif t.joins:
                        extra = f" // join <- {', '.join(t.joins)}"
                    self._w(
                        d,
                        f"transition {_ident(t.id)} first {_ident(t.source_state)} "
                        f"if {t.guard} then {_ident(t.target_state)};{extra}",
                    )
                if nested:
                    self._w(2, "}")
            self._w(1, "}")
            self._w(0)

    def _emit_allocations(self) -> None:
        """Logical part -> executable realisation. This is the SysML/Modelica bridge."""
        bound = [b for b in self.m.blocks if b.modelica_class]
        if not bound:
            return
        self._w(1, "// ----------------------------------------------------- modelica allocation")
        for b in bound:
            self._w(
                1,
                f"allocation {_ident(b.id)}_impl allocate {_ident(b.id)} to "
                f"Modelica::{b.modelica_class}; // tier {b.binding_tier}",
            )
        self._w(0)

    def _emit_verification(self) -> None:
        checks = [c for s in self.m.scenarios for c in s.checks]
        if not checks:
            return
        self._w(1, "// ----------------------------------------------------------- verification")
        for c in checks:
            self._w(1, f"verification def {_ident(c.id)} {{")
            self._w(2, f"doc /* {c.description} */")
            self._w(2, f'attribute expression : String default "{c.expression}";')
            for rid in c.requirement_ids:
                self._w(2, f"// @verifies {rid}")
            self._w(1, "}")
        self._w(0)


def emit_sysml(model: SystemModel, out_path: str | Path) -> Path:
    text = SysMLEmitter(model).emit()
    p = Path(out_path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(text, encoding="utf-8")
    return p


# ------------------------------------------------------------------------ round-trip check


@dataclass
class ParsedSysML:
    """Structural skeleton recovered from emitted text, for the round-trip check."""

    parts: set[str] = field(default_factory=set)
    part_defs: set[str] = field(default_factory=set)
    interfaces: set[tuple[str, str]] = field(default_factory=set)
    requirements: set[str] = field(default_factory=set)
    states: set[str] = field(default_factory=set)
    transitions: set[str] = field(default_factory=set)
    allocations: set[str] = field(default_factory=set)


_RE_PART = re.compile(r"^\s*part\s+(\w+)\s*:\s*(\w+)")
_RE_PART_DEF = re.compile(r"^\s*part\s+def\s+(\w+)")
_RE_REQ = re.compile(r"^\s*requirement\s+def\s+(\w+)")
_RE_IFACE = re.compile(r"^\s*interface\s+\w+\s+connect\s+([\w.]+)\s+to\s+([\w.]+)")
_RE_STATE = re.compile(r"^\s*state\s+(\w+)\s*\{")
_RE_TRANS = re.compile(r"^\s*transition\s+(\w+)\s+first")
_RE_ALLOC = re.compile(r"^\s*allocation\s+\w+\s+allocate\s+(\w+)\s+to")


def parse_back(text: str) -> ParsedSysML:
    out = ParsedSysML()
    for line in text.splitlines():
        if m := _RE_PART_DEF.match(line):
            out.part_defs.add(m.group(1))
        elif m := _RE_PART.match(line):
            out.parts.add(m.group(1))
        if m := _RE_REQ.match(line):
            out.requirements.add(m.group(1))
        if m := _RE_IFACE.match(line):
            out.interfaces.add((m.group(1), m.group(2)))
        if m := _RE_STATE.match(line):
            out.states.add(m.group(1))
        if m := _RE_TRANS.match(line):
            out.transitions.add(m.group(1))
        if m := _RE_ALLOC.match(line):
            out.allocations.add(m.group(1))
    return out


def round_trip_check(model: SystemModel, text: str) -> list[str]:
    """Every IR element must be findable in the emitted text. Returns a list of losses."""
    parsed = parse_back(text)
    problems: list[str] = []
    for b in model.blocks:
        if _ident(b.id) not in parsed.parts:
            problems.append(f"block '{b.id}' did not survive emission")
    for r in model.requirements:
        if _ident(r.id) not in parsed.requirements:
            problems.append(f"requirement '{r.id}' did not survive emission")
    for c in model.connections:
        (sb, sp), (tb, tp) = c.endpoints()
        pair = (f"{_ident(sb)}.{_ident(sp)}", f"{_ident(tb)}.{_ident(tp)}")
        if pair not in parsed.interfaces:
            problems.append(f"connection '{c.id}' did not survive emission")
    for sm in model.state_machines:
        for s in sm.states:
            if _ident(s.id) not in parsed.states:
                problems.append(f"state '{s.id}' did not survive emission")
        for t in sm.transitions:
            if _ident(t.id) not in parsed.transitions:
                problems.append(f"transition '{t.id}' did not survive emission")
    return problems


def _sysml_type(datatype: str) -> str:
    return {"real": "Real", "boolean": "Boolean", "integer": "Integer"}.get(datatype, "Real")
